### ISSUE TITLE
Where do i put my cronjob?

### ISSUE THREAD

**Issue by judaschwartz** [Deliaz/so_visitor#1]
I am not familiar with nightmare how do i get this to run in my cron job, also what steps do ineed to take to get Nightmare on my ubntu server?

**Comment by Deliaz** [comment]
Hello. 
You can set the job using these steps: 

1. `crontab -e`
2. put this line at the end: 
```
30 9 * * * xvfb-run node /home/user1/so_visitor/index.js
```
Be sure to change the path to your project folder. And tune time to run (in the example above it is 9:30 am).
