### ISSUE TITLE
Something went wrong: Error: .wait() timed out after 30000msec

### ISSUE THREAD

**Issue by kopax** [Deliaz/so_visitor#2]
I have tried to use the bot but for some reason I receive this email: 

    Something went wrong: Error: .wait() timed out after 30000msec

Things must have changed ^^,

**Comment by Deliaz** [comment]
Probably the selectors have been changed and should be updated accordingly. Unfortunately, I didn't touch this project for 3 years.

**Comment by kopax** [comment]
Of course, you don't need it anymore. 

I have checked all selectors, and the only one that was broken can be fixed with: 

```diff
- const el = document.querySelector('#top-cards span.-count');
+ const el = document.querySelector('#top-cards .js-highlight-box-badges span.fs-caption.grid--cell');
```

This should not cause the timeout error.

**Comment by Deliaz** [comment]
I am open for PR :)

**Comment by kopax** [comment]
I've just noticed the `{ show: true }` for nightmare, I will test again and PR.

Also, I will test it within `Docker` so it can be deployed quickly anywhere, are you interested?

**Comment by Deliaz** [comment]
> Also, I will test it within `Docker` so it can be deployed quickly anywhere, are you interested?

Sure, why not. 
thanks

**Comment by kopax** [comment]
Thanks to you ^^,

**Comment by kopax** [comment]
Too bad, unfortunately, I have tested the script and it work fine when I run it manually in terminal with  x11 environment.

However, it does not run with `crontab`, probably because there is no x11 environment. It does not run on a server either for the same reason. This means it also can't work within docker.

**Comment by Deliaz** [comment]
It is anyway thank you for your contribution!
